### ISSUE TITLE
Reporting a vulnerability 

### ISSUE THREAD

**Issue by NErinola** [contiki-ng/tinydtls#31]
How can we report a discovered security vulnerability? The security policy on GitHub is empty, so we do not have a contact to report a security vulnerability.

Best regards,
Nurullah Erinola

**Comment by boaks** [comment]
Just to mention:
If the vulnerability is about tinydtls, the development is done in the [eclipse/tinydtls](https://github.com/eclipse/tinydtls) repository. Check there for the "develop" branch. If you find a vulnerability also there, please follow the guidance in [www.eclipse.org - security](https://www.eclipse.org/security/).

Before you report such a vulnerability, please check, if it is already pending:

[reported vulnerabilities](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues?scope=all&state=opened&search=tinydtls)

[reported issues](https://github.com/eclipse/tinydtls/issues?q=is%3Aissue+)

(Not all bugs are vulnerabilities, especially issue in demo-apps are hardly a real vulnerability.)

**Comment by NErinola** [comment]
Thanks for the quick response.

Our finding is fixed in the [develop](https://github.com/eclipse/tinydtls/tree/develop) branch of [eclipse/tinydtls](https://github.com/eclipse/tinydtls) with [#115](https://github.com/eclipse/tinydtls/pull/115). Therefore we refrain from taking any further steps.

**Comment by boaks** [comment]
If you currently develop with contiki-ng, maybe you can check, if update tinydtls to the current develop works with it as well.

See [Update/test tinydtls to Eclipse/Tinydtls branch "develop"](https://github.com/contiki-ng/contiki-ng/discussions/1716).
